// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;
public class SuiteTests : IDisposable {
  public IWebDriver driver {get; private set;}
  public IDictionary<String, Object> vars {get; private set;}
  public IJavaScriptExecutor js {get; private set;}
  public SuiteTests()
  {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<String, Object>();
  }
  public void Dispose()
  {
    driver.Quit();
  }
  [Fact]
  public void CT09CampoQuantidadeSoliberadoaposescolherumproduto() {
    driver.Navigate().GoToUrl("https://andreldev.github.io/Almoxarifado/");
    driver.Manage().Window.Size = new System.Drawing.Size(1360, 720);
    driver.FindElement(By.Id("Quantidade")).Click();
    driver.FindElement(By.Id("Quantidade")).Click();
    {
      var element = driver.FindElement(By.Id("Quantidade"));
      Actions builder = new Actions(driver);
      builder.DoubleClick(element).Perform();
    }
    driver.FindElement(By.Id("Quantidade")).SendKeys("5643453");
    driver.FindElement(By.Id("Quantidade")).SendKeys(Keys.Enter);
    driver.FindElement(By.Id("Quantidade")).SendKeys("asdasd");
  }
}
